version: '2.2'
# networks:
#   infra_default:
#     external: true
services:
  ipsec-vpn:
    image: 'valentinvieriu/ipsec-vpn-server:1.0.0'
    restart: always
    privileged: true
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    environment: 
      VPN_IPSEC_PSK: ${VPN_IPSEC_PSK}
      VPN_USER: ${VPN_USER}
      VPN_PASSWORD: ${VPN_PASSWORD}
    volumes:
      - '/lib/modules:/lib/modules:ro'