version: '2.2'
networks:
  infra_default:
    external: true
services:
  local-redis:
    image: 'redis:4.0.1-alpine'
    restart: 'unless-stopped'
    mem_limit: '1G'
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    volumes:
      - '${ROOT_FOLDER}/redis/data:/data'

  chrome-headless:
    image: 'valentinvieriu/chrome-headless:62.0.3202.75-1'
    restart: 'unless-stopped'
    shm_size: '2G'
    restart: 'always'
    mem_limit: '2G'
    cap_add: 
      - 'SYS_ADMIN'
    command: '--ignore-certificate-errors --no-sandbox --headless --disable-gpu --hide-scrollbars -incognito --window-size=1280,1280 --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222'
    volumes: 
      - '${ROOT_FOLDER}/chromedata:/data'
    # environment: 
    #   VIRTUAL_HOST: 'ws://chrome-headless.${TLD}'

  hnews:
    image: 'valentinvieriu/hnews:1.0.3'
    restart: 'unless-stopped'
    mem_limit: '1G'
    depends_on: 
      - local-redis
    command: 'node --optimize_for_size --max_old_space_size=460 --gc_interval=100 server.js'
    networks:
      - default
      - infra_default
    environment:
      NODE_ENV: 'production'
      REDIS_URL: '${REDIS_URL}'
      THUMB_BASE_URL: 'http://node-screenshots:3000'
      VIRTUAL_HOST: 'https://hnews.${TLD},https://hnews.xyz'
      EXCLUDE_BASIC_AUTH: 'true'

  kue:
    image: 'valentinvieriu/booksclub:kue-1.0.1'
    restart: 'unless-stopped'
    mem_limit: '512M'
    depends_on:
      - local-redis
    networks:
      - default
      - infra_default
    environment:
      NODE_ENV: 'production'
      REDIS_URL: '${REDIS_URL}'
      VIRTUAL_HOST: 'https://kue.hnews.${TLD}'
      GZIP_COMPRESSION_TYPE: 'text/html text/plain text/css application/javascript application/json'

  node-screenshots:
    image: 'valentinvieriu/node-screenshots:1.0.3'
    restart: 'unless-stopped'
    depends_on:
      - local-redis
      - chrome-headless
    mem_limit: '1G'
    environment:
      FILES_CLEAN_TIMEOUT: '10'
      WATCH_QUEUE: '1'
      NODE_ENV: 'production'
      REDIS_URL: '${REDIS_URL}'
      REMOTE_HOST: 'chrome-headless'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthcheck']
      interval: 1m
      timeout: 10s
      retries: 3
    volumes: 
      - '${ROOT_FOLDER}/screenshots:/app/screenshots'