version: '2.2'
# networks:
#   infra_default:
#     external: true
volumes:
  nvidia_driver_384.59:
    external:
      name: nvidia_driver_384.59
services:
  nvidia-test:
    # image: 'nvidia/cuda'
    image: 'nvidia/cuda:8.0-devel-ubuntu16.04'
    # image: 'nvidia/cuda:8.0-cudnn7-runtime-ubuntu16.04'
    command: 'nvidia-smi'
    devices: 
      - '/dev/nvidia0:/dev/nvidia0'
      - '/dev/nvidiactl:/dev/nvidiactl'
      - '/dev/nvidia-uvm:/dev/nvidia-uvm'
      - '/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools'
    volumes:
      - 'nvidia_driver_384.59:/usr/local/nvidia:ro'
  torch-rnn:
    image: 'valentinvieriu/torch-rnn:1.0.2'
    environment:
      TERM: screen
    # command: 'nvidia-smi'
    # command: |
    #   python scripts/preprocess.py
    #     --input_txt /root/data/input/clickbait/clickbait.txt
    #     --output_h5 /root/data/input/clickbait/clickbait.h5
    #     --output_json /root/data/input/clickbait/clickbait.json
    # command: |
    #   th sample.lua
    #       -checkpoint /root/data/models/model04/checkpoint_10000.t7
    #       -length 5000
    #       -start_text "# It's the year 2044, and the real world has become an ugly place"
    #       -sample 1
    #       -temperature 0.8
    #       -gpu 0
    #       -gpu_backend cuda
    #       -verbose 1
    #       -stream 1
    command: |
      th train.lua
        -input_h5 /root/data/input/clickbait/clickbait.h5
        -input_json /root/data/input/clickbait/clickbait.json
        -checkpoint_every 10000
        -checkpoint_name /root/data/models/clickbait/model01/checkpoint
        -init_from /root/data/models/clickbait/model01/final
        -rnn_size 2048
        -num_layers 3
        -dropout 0.2
        -learning_rate 0.00005
        -batch_size 128
        -seq_length 80
        -max_epochs 32
        -print_every 1000
        -gpu 0
        -gpu_backend cuda
        -cudnn 1
        -cudnn_fastest 1
    devices: 
      - '/dev/nvidia0:/dev/nvidia0'
      - '/dev/nvidiactl:/dev/nvidiactl'
      - '/dev/nvidia-uvm:/dev/nvidia-uvm'
      - '/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools'
    volumes:
      - 'nvidia_driver_384.59:/usr/local/nvidia:ro'
      - '${ROOT_FOLDER}/torch-rnn/data:/root/data'
